/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import javax.swing.JFrame;

/**
 *
 * @author REAL COMPUTERS
 */
public class dhashbord extends javax.swing.JFrame {
 database_con CO=new database_con();
 String account="";
 String doctore="";
 String paitent="";
 String Visits="";
 String statement="";
 
   
    public dhashbord() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       CO.fillComboBox(sta,"SELECT concat(rn_no)receipts  from `receipts`","receipts");
       CO.fillComboBox(p,"select concat (p_no,',',p_name,',',p_tell,',',p_sex,',',p_birth)patentes from  `patentes`","patentes");
       CO.fillComboBox(vi,"select concat (v_no,',',p_no,',',d_no,',',prise,',',v_date)visits from `visits`","visits") ;
       CO.fillComboBox(d,"select concat (d_no,',',d_name,',',d_taype)doctores from `doctores`","doctores");
      
        
        
      CO.getValue("SELECT count(user_no)tirada FROM users", "tirada", t1);
        CO.getValue("SELECT count(d_no)tirada FROM doctores", "tirada", t2);
        CO.getValue("SELECT count(p_no)tirada FROM patentes", "tirada", t4);
     //   CO.getValue("SELECT sum(ser_no)tirada FROM services", "tirada", t4);
        CO.getValue("SELECT count(oper_no)tirada FROM operations", "tirada", t5);
        CO.getValue("SELECT count(v_no)tirada FROM visits", "tirada", t3);
        CO.getValue("SELECT count(pr_no)tirada FROM prescriptions", "tirada", t6);
        CO.getValue("SELECT count(rn_no)tirada FROM receipts", "tirada", t12);
        CO.getValue("SELECT count(balance)tirada FROM account", "tirada", t8);
        CO.getValue("SELECT count(bils_no)tirada FROM bills3", "tirada", t10);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSMaterialButtonRectangleBeanInfo1 = new rojerusan.RSMaterialButtonRectangleBeanInfo();
        jPanel4 = new javax.swing.JPanel();
        rSButtonIconI5 = new rojerusan.RSButtonIconI();
        rSLabelImage4 = new rojerusan.RSLabelImage();
        jLabel26 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        a4 = new javax.swing.JTabbedPane();
        admin = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        rSMaterialButtonRectangle15 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle16 = new rojerusan.RSMaterialButtonRectangle();
        rSLabelImage6 = new rojerusan.RSLabelImage();
        reges = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle5 = new rojerusan.RSMaterialButtonRectangle();
        rSLabelImage1 = new rojerusan.RSLabelImage();
        doc = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        rSMaterialButtonRectangle11 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle12 = new rojerusan.RSMaterialButtonRectangle();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        rSMaterialButtonRectangle13 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle14 = new rojerusan.RSMaterialButtonRectangle();
        rSLabelImage5 = new rojerusan.RSLabelImage();
        maaliyad = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rSMaterialButtonRectangle7 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle8 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle9 = new rojerusan.RSMaterialButtonRectangle();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        rSMaterialButtonRectangle10 = new rojerusan.RSMaterialButtonRectangle();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        report = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne1 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne2 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial1 = new RSMaterialComponent.RSComboBoxMaterial();
        sta = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel12 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne25 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne26 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial2 = new RSMaterialComponent.RSComboBoxMaterial();
        accoun1 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel3 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne3 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne4 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial3 = new RSMaterialComponent.RSComboBoxMaterial();
        d = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel5 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne5 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne6 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial5 = new RSMaterialComponent.RSComboBoxMaterial();
        p = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel25 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne7 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne8 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial7 = new RSMaterialComponent.RSComboBoxMaterial();
        vi = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel31 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne11 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne12 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial8 = new RSMaterialComponent.RSComboBoxMaterial();
        vi1 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel32 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne13 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne14 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial11 = new RSMaterialComponent.RSComboBoxMaterial();
        vi2 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel33 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne15 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne16 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial12 = new RSMaterialComponent.RSComboBoxMaterial();
        vi3 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel34 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne17 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne18 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial13 = new RSMaterialComponent.RSComboBoxMaterial();
        vi4 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel35 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne19 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne20 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial14 = new RSMaterialComponent.RSComboBoxMaterial();
        vi5 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel36 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne21 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne22 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial15 = new RSMaterialComponent.RSComboBoxMaterial();
        vi6 = new RSMaterialComponent.RSComboBoxMaterial();
        jPanel37 = new javax.swing.JPanel();
        rSButtonMaterialGradientOne23 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSButtonMaterialGradientOne24 = new RSMaterialComponent.RSButtonMaterialGradientOne();
        rSComboBoxMaterial16 = new RSMaterialComponent.RSComboBoxMaterial();
        vi7 = new RSMaterialComponent.RSComboBoxMaterial();
        rSLabelImage7 = new rojerusan.RSLabelImage();
        home = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        rSLabelImage8 = new rojerusan.RSLabelImage();
        jLabel8 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        t12 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rep.setBackground(new java.awt.Color(0, 0, 0));
        rep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/report.png"))); // NOI18N
        rep.setText("    report                             ");
        rep.setColorText(new java.awt.Color(153, 0, 255));
        rep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repActionPerformed(evt);
            }
        });
        jPanel4.add(rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 720, 340, 70));

        rSButtonIconI5.setBackground(new java.awt.Color(0, 0, 0));
        rSButtonIconI5.setForeground(new java.awt.Color(153, 0, 255));
        rSButtonIconI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/home (1).png"))); // NOI18N
        rSButtonIconI5.setText("      Home                           ");
        rSButtonIconI5.setColorText(new java.awt.Color(153, 0, 255));
        rSButtonIconI5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonIconI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI5ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButtonIconI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 340, 80));

        d1.setBackground(new java.awt.Color(0, 0, 0));
        d1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/doctors.png"))); // NOI18N
        d1.setText("Doctores                     ");
        d1.setColorText(new java.awt.Color(153, 0, 255));
        d1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        jPanel4.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 630, 330, 80));

        reg.setBackground(new java.awt.Color(0, 0, 0));
        reg.setForeground(new java.awt.Color(153, 0, 255));
        reg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/regestration 2.png"))); // NOI18N
        reg.setText("     Regestration                 ");
        reg.setColorText(new java.awt.Color(153, 0, 255));
        reg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });
        jPanel4.add(reg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 340, 90));

        rep1.setBackground(new java.awt.Color(0, 0, 0));
        rep1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/log-in (1).png"))); // NOI18N
        rep1.setText("LogOut                           ");
        rep1.setColorHover(new java.awt.Color(204, 0, 0));
        rep1.setColorText(new java.awt.Color(153, 0, 255));
        rep1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep1ActionPerformed(evt);
            }
        });
        jPanel4.add(rep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 800, 340, 70));

        aad.setBackground(new java.awt.Color(0, 0, 0));
        aad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/users_1.png"))); // NOI18N
        aad.setText("    Admin                              ");
        aad.setColorText(new java.awt.Color(153, 0, 255));
        aad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aadActionPerformed(evt);
            }
        });
        jPanel4.add(aad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 350, 70));

        rSLabelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/dental-clinic.png"))); // NOI18N
        jPanel4.add(rSLabelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Dental clinck Systeam");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        fin1.setBackground(new java.awt.Color(0, 0, 0));
        fin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dhashbord_im/bills.png"))); // NOI18N
        fin1.setText("finince                       ");
        fin1.setColorText(new java.awt.Color(153, 0, 255));
        fin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fin1ActionPerformed(evt);
            }
        });
        jPanel4.add(fin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 540, 330, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 410, 1070));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l2.setText("User Name");
        jPanel11.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 60, 140, -1));

        jLabel2.setText("jLabel2");
        jPanel11.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 60, 0, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 3)); // NOI18N
        jLabel3.setText("|");
        jPanel11.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1066, 20, 10, 60));

        l1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l1.setText("User Name");
        jPanel11.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 20, 140, -1));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/users.png"))); // NOI18N
        jPanel11.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 10, 110, 90));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel23.setText("Dental clinck ");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, -1, 50));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel24.setText("Manegment  Systeam");
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, 50));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/tooth (1).png"))); // NOI18N
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/comments.png"))); // NOI18N
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/notification.png"))); // NOI18N
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 30, -1, -1));

        getContentPane().add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, -10, 1560, 120));

        admin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/users.png"))); // NOI18N
        admin.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel51.setText("Doctores");
        admin.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/doctors.png"))); // NOI18N
        admin.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel53.setText("Users");
        admin.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        rSMaterialButtonRectangle15.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle15.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle15ActionPerformed(evt);
            }
        });
        admin.add(rSMaterialButtonRectangle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 340, 160));

        rSMaterialButtonRectangle16.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle16.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle16ActionPerformed(evt);
            }
        });
        admin.add(rSMaterialButtonRectangle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 340, 160));

        rSLabelImage6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/aaa3.png"))); // NOI18N
        admin.add(rSLabelImage6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, -40, 1560, 900));

        a4.addTab("Admin", admin);

        reges.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/visits.png"))); // NOI18N
        reges.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/servise.png"))); // NOI18N
        reges.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setText("services");
        reges.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel18.setText("Visits");
        reges.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 100, -1));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle2.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle2ActionPerformed(evt);
            }
        });
        reges.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 340, 160));

        rSMaterialButtonRectangle5.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle5.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle5ActionPerformed(evt);
            }
        });
        reges.add(rSMaterialButtonRectangle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 340, 160));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/dental6.jpg"))); // NOI18N
        reges.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1620, 900));

        a4.addTab("Regestration", reges);

        doc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        doc.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(762, 5, -1, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel42.setText("Paitenta");
        doc.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a_dentelclinck/prescription_1.png"))); // NOI18N
        doc.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/PATENTS.png"))); // NOI18N
        doc.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, 180));

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel45.setText("Oprations");
        doc.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel46.setText("Prescription");
        doc.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        rSMaterialButtonRectangle11.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle11.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle11ActionPerformed(evt);
            }
        });
        doc.add(rSMaterialButtonRectangle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 340, 160));

        rSMaterialButtonRectangle12.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle12.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle12ActionPerformed(evt);
            }
        });
        doc.add(rSMaterialButtonRectangle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 340, 160));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/prescreption table.png"))); // NOI18N
        doc.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("Customer prescription");
        doc.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/opration.png"))); // NOI18N
        doc.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, -1, -1));

        rSMaterialButtonRectangle13.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle13.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/prescreption table.png"))); // NOI18N
        rSMaterialButtonRectangle13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle13ActionPerformed(evt);
            }
        });
        doc.add(rSMaterialButtonRectangle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 340, 160));

        rSMaterialButtonRectangle14.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle14.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/prescreption table.png"))); // NOI18N
        rSMaterialButtonRectangle14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle14ActionPerformed(evt);
            }
        });
        doc.add(rSMaterialButtonRectangle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 340, 160));

        rSLabelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/d1 1.jpg"))); // NOI18N
        doc.add(rSLabelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 900));

        a4.addTab("Doctor", doc);

        maaliyad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setText("Bills");
        maaliyad.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/receipt (1)_1.png"))); // NOI18N
        maaliyad.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 130, 140));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/money.png"))); // NOI18N
        maaliyad.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 130, 130));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel20.setText("Recipt");
        maaliyad.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel21.setText("Amount");
        maaliyad.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/amount 111.png"))); // NOI18N
        maaliyad.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        rSMaterialButtonRectangle7.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle7.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle7ActionPerformed(evt);
            }
        });
        maaliyad.add(rSMaterialButtonRectangle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 340, 160));

        rSMaterialButtonRectangle8.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle8.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle8ActionPerformed(evt);
            }
        });
        maaliyad.add(rSMaterialButtonRectangle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 350, 160));

        rSMaterialButtonRectangle9.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle9.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/bank circle.png"))); // NOI18N
        rSMaterialButtonRectangle9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle9ActionPerformed(evt);
            }
        });
        maaliyad.add(rSMaterialButtonRectangle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 340, 160));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/bank_1.png"))); // NOI18N
        maaliyad.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel40.setText("Account");
        maaliyad.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        rSMaterialButtonRectangle10.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonRectangle10.setForeground(new java.awt.Color(0, 0, 0));
        rSMaterialButtonRectangle10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/bank circle.png"))); // NOI18N
        rSMaterialButtonRectangle10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle10ActionPerformed(evt);
            }
        });
        maaliyad.add(rSMaterialButtonRectangle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 340, 160));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/fin1111.jpg"))); // NOI18N
        maaliyad.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 900));

        a4.addTab("Finince", maaliyad);

        report.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        report.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "recipt and amount report", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne1.setText("Single");
        rSButtonMaterialGradientOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialGradientOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne2.setText("All");
        rSButtonMaterialGradientOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialGradientOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel2.add(rSComboBoxMaterial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        sta.setBackground(new java.awt.Color(32, 131, 255));
        sta.setEditable(true);
        sta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Statement" }));
        sta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staActionPerformed(evt);
            }
        });
        jPanel2.add(sta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Account  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne25.setText("Single");
        rSButtonMaterialGradientOne25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne25ActionPerformed(evt);
            }
        });
        jPanel12.add(rSButtonMaterialGradientOne25, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne26.setText("All");
        rSButtonMaterialGradientOne26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne26ActionPerformed(evt);
            }
        });
        jPanel12.add(rSButtonMaterialGradientOne26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel12.add(rSComboBoxMaterial2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        accoun1.setBackground(new java.awt.Color(32, 131, 255));
        accoun1.setEditable(true);
        accoun1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Account" }));
        accoun1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accoun1ActionPerformed(evt);
            }
        });
        jPanel12.add(accoun1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 370, 140));

        report.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 370, 140));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctores Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne3.setText("Single");
        rSButtonMaterialGradientOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne3ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialGradientOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne4.setText("All");
        rSButtonMaterialGradientOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne4ActionPerformed(evt);
            }
        });
        jPanel3.add(rSButtonMaterialGradientOne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel3.add(rSComboBoxMaterial3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        d.setBackground(new java.awt.Color(32, 131, 255));
        d.setEditable(true);
        d.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctore" }));
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        jPanel3.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        report.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 370, 140));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patients Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne5.setText("Single");
        rSButtonMaterialGradientOne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne5ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonMaterialGradientOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne6.setText("All");
        rSButtonMaterialGradientOne6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne6ActionPerformed(evt);
            }
        });
        jPanel5.add(rSButtonMaterialGradientOne6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel5.add(rSComboBoxMaterial5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        p.setBackground(new java.awt.Color(32, 131, 255));
        p.setEditable(true);
        p.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "patient" }));
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        jPanel5.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        report.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 370, 140));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne7.setText("Single");
        rSButtonMaterialGradientOne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne7ActionPerformed(evt);
            }
        });
        jPanel25.add(rSButtonMaterialGradientOne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne8.setText("All");
        rSButtonMaterialGradientOne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne8ActionPerformed(evt);
            }
        });
        jPanel25.add(rSButtonMaterialGradientOne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel25.add(rSComboBoxMaterial7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi.setBackground(new java.awt.Color(32, 131, 255));
        vi.setEditable(true);
        vi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viActionPerformed(evt);
            }
        });
        jPanel25.add(vi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, 30));

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne11.setText("Single");
        rSButtonMaterialGradientOne11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne11ActionPerformed(evt);
            }
        });
        jPanel31.add(rSButtonMaterialGradientOne11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne12.setText("All");
        rSButtonMaterialGradientOne12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne12ActionPerformed(evt);
            }
        });
        jPanel31.add(rSButtonMaterialGradientOne12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel31.add(rSComboBoxMaterial8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi1.setBackground(new java.awt.Color(32, 131, 255));
        vi1.setEditable(true);
        vi1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi1ActionPerformed(evt);
            }
        });
        jPanel31.add(vi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel25.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 370, 140));

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne13.setText("Single");
        rSButtonMaterialGradientOne13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne13ActionPerformed(evt);
            }
        });
        jPanel32.add(rSButtonMaterialGradientOne13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne14.setText("All");
        rSButtonMaterialGradientOne14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne14ActionPerformed(evt);
            }
        });
        jPanel32.add(rSButtonMaterialGradientOne14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel32.add(rSComboBoxMaterial11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi2.setBackground(new java.awt.Color(32, 131, 255));
        vi2.setEditable(true);
        vi2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi2ActionPerformed(evt);
            }
        });
        jPanel32.add(vi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel33.setBackground(new java.awt.Color(255, 255, 255));
        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne15.setText("Single");
        rSButtonMaterialGradientOne15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne15ActionPerformed(evt);
            }
        });
        jPanel33.add(rSButtonMaterialGradientOne15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne16.setText("All");
        rSButtonMaterialGradientOne16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne16ActionPerformed(evt);
            }
        });
        jPanel33.add(rSButtonMaterialGradientOne16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel33.add(rSComboBoxMaterial12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi3.setBackground(new java.awt.Color(32, 131, 255));
        vi3.setEditable(true);
        vi3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi3ActionPerformed(evt);
            }
        });
        jPanel33.add(vi3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 370, 140));

        jPanel25.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 370, 140));

        jPanel34.setBackground(new java.awt.Color(255, 255, 255));
        jPanel34.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne17.setText("Single");
        rSButtonMaterialGradientOne17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne17ActionPerformed(evt);
            }
        });
        jPanel34.add(rSButtonMaterialGradientOne17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne18.setText("All");
        rSButtonMaterialGradientOne18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne18ActionPerformed(evt);
            }
        });
        jPanel34.add(rSButtonMaterialGradientOne18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel34.add(rSComboBoxMaterial13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi4.setBackground(new java.awt.Color(32, 131, 255));
        vi4.setEditable(true);
        vi4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi4ActionPerformed(evt);
            }
        });
        jPanel34.add(vi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel35.setBackground(new java.awt.Color(255, 255, 255));
        jPanel35.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne19.setText("Single");
        rSButtonMaterialGradientOne19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne19ActionPerformed(evt);
            }
        });
        jPanel35.add(rSButtonMaterialGradientOne19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne20.setText("All");
        rSButtonMaterialGradientOne20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne20ActionPerformed(evt);
            }
        });
        jPanel35.add(rSButtonMaterialGradientOne20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel35.add(rSComboBoxMaterial14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi5.setBackground(new java.awt.Color(32, 131, 255));
        vi5.setEditable(true);
        vi5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi5ActionPerformed(evt);
            }
        });
        jPanel35.add(vi5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel34.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 370, 140));

        jPanel36.setBackground(new java.awt.Color(255, 255, 255));
        jPanel36.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne21.setText("Single");
        rSButtonMaterialGradientOne21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne21ActionPerformed(evt);
            }
        });
        jPanel36.add(rSButtonMaterialGradientOne21, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne22.setText("All");
        rSButtonMaterialGradientOne22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne22ActionPerformed(evt);
            }
        });
        jPanel36.add(rSButtonMaterialGradientOne22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel36.add(rSComboBoxMaterial15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi6.setBackground(new java.awt.Color(32, 131, 255));
        vi6.setEditable(true);
        vi6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi6ActionPerformed(evt);
            }
        });
        jPanel36.add(vi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel37.setBackground(new java.awt.Color(255, 255, 255));
        jPanel37.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Visits  Repot", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMaterialGradientOne23.setText("Single");
        rSButtonMaterialGradientOne23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne23ActionPerformed(evt);
            }
        });
        jPanel37.add(rSButtonMaterialGradientOne23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 40));

        rSButtonMaterialGradientOne24.setText("All");
        rSButtonMaterialGradientOne24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialGradientOne24ActionPerformed(evt);
            }
        });
        jPanel37.add(rSButtonMaterialGradientOne24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 40));

        rSComboBoxMaterial16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User" }));
        jPanel37.add(rSComboBoxMaterial16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 260, -1));

        vi7.setBackground(new java.awt.Color(32, 131, 255));
        vi7.setEditable(true);
        vi7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VIsits" }));
        vi7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vi7ActionPerformed(evt);
            }
        });
        jPanel37.add(vi7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 30));

        jPanel36.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 370, 140));

        jPanel34.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 270, 370, 140));

        jPanel25.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 370, 140));

        report.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 370, 140));

        rSLabelImage7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/arr1.jpg"))); // NOI18N
        report.add(rSLabelImage7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 900));

        a4.addTab("Report", report);

        home.setBackground(new java.awt.Color(255, 255, 255));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        home.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 150, -1, -1));

        rSLabelImage8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/h1.jpg"))); // NOI18N
        home.add(rSLabelImage8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 360));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/opration.png"))); // NOI18N
        home.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        t5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t5.setText("NuMBER");
        home.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 600, 90, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Total of patient ");
        home.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, -1, -1));

        t4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t4.setText("Number");
        home.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 430, 60, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/servise.png"))); // NOI18N
        home.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/amountname 22.png"))); // NOI18N
        home.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel37.setText("Total of  biils");
        home.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 710, 130, -1));

        t10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t10.setText("jLabel1");
        home.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 760, 40, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/doctors.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        home.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 130, 120));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setText("Total of paitent");
        home.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 400, -1, -1));

        t2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t2.setText("Number");
        home.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 60, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/prescription.png"))); // NOI18N
        home.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 540, -1, 120));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Total of prescriptions");
        home.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 550, -1, -1));

        t6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t6.setText("jLabel1");
        home.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 600, 90, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/balance.png"))); // NOI18N
        home.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 700, -1, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel39.setText("Account balance");
        home.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 710, 230, -1));

        t8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t8.setText("jLabel1");
        home.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 750, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/users_1.png"))); // NOI18N
        home.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Total of Users");
        home.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        t1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t1.setText("users");
        home.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/PATEENT_FORM.png"))); // NOI18N
        home.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 550, -1, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setText("Total of Visits");
        home.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, -1, -1));

        t3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t3.setText("NuMBER");
        home.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 30, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/receipt (1)_1.png"))); // NOI18N
        home.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 710, -1, 140));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel38.setText("Total of  Recept");
        home.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 720, 160, -1));

        t12.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        t12.setText("jLabel1");
        home.add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 760, 70, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Total of Doctores");
        home.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, -1, -1));

        a4.addTab("Home", home);

        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 1540, 930));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI5ActionPerformed
        // TODO add your handling code here:
   a4.setSelectedComponent(home);
    }//GEN-LAST:event_rSButtonIconI5ActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        
            a4.setSelectedComponent(reges);
    }//GEN-LAST:event_regActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:
        a4.setSelectedComponent(doc);
    }//GEN-LAST:event_d1ActionPerformed

    private void repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repActionPerformed
        // TODO add your handling code here:
        
           a4.setSelectedComponent(report);
    }//GEN-LAST:event_repActionPerformed

    private void buttonBadges2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBadges2ActionPerformed

    private void rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep1ActionPerformed
     login_s l=new login_s();
     l.show();
     this.hide();
    }//GEN-LAST:event_rep1ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        // TODO add your handling code here:
        visits_view v= new visits_view();
        v.show();

    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void rSMaterialButtonRectangle5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle5ActionPerformed
        // TODO add your handling code here:
        servise_table s =new servise_table();
        s.show();
        
        
    }//GEN-LAST:event_rSMaterialButtonRectangle5ActionPerformed

    private void aadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aadActionPerformed
        // TODO add your handling code here:
              a4.setSelectedComponent(admin);
    }//GEN-LAST:event_aadActionPerformed

    private void rSButtonMaterialGradientOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne2ActionPerformed
        // TODO add your handling code here:
          String sql="call sta_re()";
     CO.report("src\\a_dentelclinck\\srt_all.jrxml", sql);
    }//GEN-LAST:event_rSButtonMaterialGradientOne2ActionPerformed

    private void staActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staActionPerformed
        // TODO add your handling code here:
          String []name=sta.getSelectedItem().toString().split(",");
      statement=name[0];
    }//GEN-LAST:event_staActionPerformed

    private void rSButtonMaterialGradientOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne1ActionPerformed
        // TODO add your handling code here:
              String sql="call sta_single('"+statement+"')";
     CO.report("src\\a_dentelclinck\\sta_report.jrxml", sql);
       
    }//GEN-LAST:event_rSButtonMaterialGradientOne1ActionPerformed

    private void rSButtonMaterialGradientOne6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne6ActionPerformed
        // TODO add your handling code here:
            String sql="call people_view ()";
     CO.report("src\\a_dentelclinck\\patients_report_all.jrxml", sql);
    }//GEN-LAST:event_rSButtonMaterialGradientOne6ActionPerformed

    private void rSButtonMaterialGradientOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne4ActionPerformed
        // TODO add your handling code here:
              String sql="call doctores_view ()";
     CO.report("src\\a_dentelclinck\\doctore.jrxml", sql);
        
      
    }//GEN-LAST:event_rSButtonMaterialGradientOne4ActionPerformed

    private void rSMaterialButtonRectangle8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle8ActionPerformed
        // TODO add your handling code here:
        recpt_view r = new recpt_view ();
        r.show();
    
                
    }//GEN-LAST:event_rSMaterialButtonRectangle8ActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
          String []name=p.getSelectedItem().toString().split(",");
     paitent=name[0];
    }//GEN-LAST:event_pActionPerformed

    private void rSButtonMaterialGradientOne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne5ActionPerformed
        // TODO add your handling code here:
           String sql="call patient_single('"+paitent+"')";
       CO.report("src\\a_dentelclinck\\patients_report_all.jrxml", sql);
    }//GEN-LAST:event_rSButtonMaterialGradientOne5ActionPerformed

    private void rSButtonMaterialGradientOne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne8ActionPerformed
        // TODO add your handling code here:
                String sql="call visits_view_new()";
     CO.report("src\\a_dentelclinck\\visit.jrxml", sql);
       
     
    }//GEN-LAST:event_rSButtonMaterialGradientOne8ActionPerformed

    private void rSButtonMaterialGradientOne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne7ActionPerformed
        // TODO add your handling code here:
             String sql="call visit_single('"+ Visits+"')";
       CO.report("src\\a_dentelclinck\\visit.jrxml", sql);
   
    }//GEN-LAST:event_rSButtonMaterialGradientOne7ActionPerformed

    private void rSButtonMaterialGradientOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne3ActionPerformed
        // TODO add your handling code here:
           String sql="call  single_doctor('"+ doctore+"')";
       CO.report("src\\a_dentelclinck\\doctore.jrxml", sql);
    }//GEN-LAST:event_rSButtonMaterialGradientOne3ActionPerformed

    private void viActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viActionPerformed
        // TODO add your handling code here:
                  String []name=vi.getSelectedItem().toString().split(",");
     Visits=name[0];
        
    }//GEN-LAST:event_viActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
                  String []name=d.getSelectedItem().toString().split(",");
     doctore=name[0];

      // TODO add your handling code here:
    }//GEN-LAST:event_dActionPerformed

    private void rSMaterialButtonRectangle9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle9ActionPerformed
        // TODO add your handling code here:
        amount_table a= new amount_table();
        a.show();
       
    }//GEN-LAST:event_rSMaterialButtonRectangle9ActionPerformed

    private void rSMaterialButtonRectangle10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle10ActionPerformed
        // TODO add your handling code here:
        account_view a= new account_view();
        a.show();
    
        
    }//GEN-LAST:event_rSMaterialButtonRectangle10ActionPerformed

    private void fin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fin1ActionPerformed
        // TODO add your handling code here:
         a4.setSelectedComponent(maaliyad);
    }//GEN-LAST:event_fin1ActionPerformed

    private void rSMaterialButtonRectangle7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle7ActionPerformed
        // TODO add your handling code here:

        bills_view b= new bills_view();
        b.show();
       
    }//GEN-LAST:event_rSMaterialButtonRectangle7ActionPerformed

    private void rSMaterialButtonRectangle11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle11ActionPerformed
        // TODO add your handling code here:
        prescription_table pr=new  prescription_table();
        pr.show();
        
    }//GEN-LAST:event_rSMaterialButtonRectangle11ActionPerformed

    private void rSMaterialButtonRectangle12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle12ActionPerformed
Patent_table p= new  Patent_table();
p.show();
        
    }//GEN-LAST:event_rSMaterialButtonRectangle12ActionPerformed

    private void rSMaterialButtonRectangle13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle13ActionPerformed
        // TODO add your handling code here:
       c_pr_table pr= new c_pr_table ();
       pr.show();
        
    }//GEN-LAST:event_rSMaterialButtonRectangle13ActionPerformed

    private void rSMaterialButtonRectangle14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle14ActionPerformed
        // TODO add your handling code here:
        opretin_view v = new opretin_view();
        v.show();
        
    }//GEN-LAST:event_rSMaterialButtonRectangle14ActionPerformed

    private void rSButtonMaterialGradientOne11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne11ActionPerformed

    private void rSButtonMaterialGradientOne12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne12ActionPerformed

    private void vi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vi1ActionPerformed

    private void rSButtonMaterialGradientOne13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne13ActionPerformed

    private void rSButtonMaterialGradientOne14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne14ActionPerformed

    private void vi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vi2ActionPerformed

    private void rSButtonMaterialGradientOne15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne15ActionPerformed

    private void rSButtonMaterialGradientOne16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne16ActionPerformed

    private void vi3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vi3ActionPerformed

    private void rSButtonMaterialGradientOne17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne17ActionPerformed

    private void rSButtonMaterialGradientOne18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne18ActionPerformed

    private void vi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vi4ActionPerformed

    private void rSButtonMaterialGradientOne19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne19ActionPerformed

    private void rSButtonMaterialGradientOne20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne20ActionPerformed

    private void vi5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vi5ActionPerformed

    private void rSButtonMaterialGradientOne21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne21ActionPerformed

    private void rSButtonMaterialGradientOne22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne22ActionPerformed

    private void vi6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vi6ActionPerformed

    private void rSButtonMaterialGradientOne23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne23ActionPerformed

    private void rSButtonMaterialGradientOne24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne24ActionPerformed

    private void vi7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vi7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vi7ActionPerformed

    private void rSButtonMaterialGradientOne25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne25ActionPerformed

    private void rSButtonMaterialGradientOne26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialGradientOne26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialGradientOne26ActionPerformed

    private void accoun1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accoun1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accoun1ActionPerformed

    private void rSMaterialButtonRectangle15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle15ActionPerformed
        // TODO add your handling code here:
        DoctorsView d= new DoctorsView();
        d.show();
    }//GEN-LAST:event_rSMaterialButtonRectangle15ActionPerformed

    private void rSMaterialButtonRectangle16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle16ActionPerformed
        // TODO add your handling code here:
        user_taple u= new user_taple();
        u.show();
        
    }//GEN-LAST:event_rSMaterialButtonRectangle16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dhashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dhashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dhashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dhashbord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dhashbord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane a4;
    public static final transient rojerusan.RSButtonIconI aad = new rojerusan.RSButtonIconI();
    private RSMaterialComponent.RSComboBoxMaterial accoun1;
    private javax.swing.JPanel admin;
    private RSMaterialComponent.RSComboBoxMaterial d;
    public static final transient rojerusan.RSButtonIconI d1 = new rojerusan.RSButtonIconI();
    private javax.swing.JPanel doc;
    public static final transient rojerusan.RSButtonIconI fin1 = new rojerusan.RSButtonIconI();
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    public static final transient javax.swing.JLabel l1 = new javax.swing.JLabel();
    public static final transient javax.swing.JLabel l2 = new javax.swing.JLabel();
    private javax.swing.JPanel maaliyad;
    private RSMaterialComponent.RSComboBoxMaterial p;
    private rojerusan.RSButtonIconI rSButtonIconI5;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne1;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne11;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne12;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne13;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne14;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne15;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne16;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne17;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne18;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne19;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne2;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne20;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne21;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne22;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne23;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne24;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne25;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne26;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne3;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne4;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne5;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne6;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne7;
    private RSMaterialComponent.RSButtonMaterialGradientOne rSButtonMaterialGradientOne8;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial1;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial11;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial12;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial13;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial14;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial15;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial16;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial2;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial3;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial5;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial7;
    private RSMaterialComponent.RSComboBoxMaterial rSComboBoxMaterial8;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelImage rSLabelImage3;
    private rojerusan.RSLabelImage rSLabelImage4;
    private rojerusan.RSLabelImage rSLabelImage5;
    private rojerusan.RSLabelImage rSLabelImage6;
    private rojerusan.RSLabelImage rSLabelImage7;
    private rojerusan.RSLabelImage rSLabelImage8;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle10;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle11;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle12;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle13;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle14;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle15;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle16;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle7;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle8;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle9;
    private rojerusan.RSMaterialButtonRectangleBeanInfo rSMaterialButtonRectangleBeanInfo1;
    public static final transient rojerusan.RSButtonIconI reg = new rojerusan.RSButtonIconI();
    private javax.swing.JPanel reges;
    public static final rojerusan.RSButtonIconI rep = new rojerusan.RSButtonIconI();
    public static final rojerusan.RSButtonIconI rep1 = new rojerusan.RSButtonIconI();
    private javax.swing.JPanel report;
    private RSMaterialComponent.RSComboBoxMaterial sta;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t8;
    private RSMaterialComponent.RSComboBoxMaterial vi;
    private RSMaterialComponent.RSComboBoxMaterial vi1;
    private RSMaterialComponent.RSComboBoxMaterial vi2;
    private RSMaterialComponent.RSComboBoxMaterial vi3;
    private RSMaterialComponent.RSComboBoxMaterial vi4;
    private RSMaterialComponent.RSComboBoxMaterial vi5;
    private RSMaterialComponent.RSComboBoxMaterial vi6;
    private RSMaterialComponent.RSComboBoxMaterial vi7;
    // End of variables declaration//GEN-END:variables
}
