/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import javax.swing.JFrame;

/**
 *
 * @author REAL COMPUTERS
 */
public class DoctorsView extends javax.swing.JFrame {
database_con dd=new database_con();
    public DoctorsView() {
        this.setLocationRelativeTo(this);
        initComponents();
        String sql = "CALL `doctores_view`()";
        dd.viewTable(sql, d_table);
                     this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //dd.viewTable(sql, tt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rSButtonIconI1 = new rojerusan.RSButtonIconI();
        jLabel3 = new javax.swing.JLabel();
        rSButtonIconI2 = new rojerusan.RSButtonIconI();
        rSButtonIconI4 = new rojerusan.RSButtonIconI();
        rSButtonIconI3 = new rojerusan.RSButtonIconI();
        rSButtonIconI5 = new rojerusan.RSButtonIconI();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        d_table = new rojeru_san.complementos.TableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonIconI1.setBackground(new java.awt.Color(0, 0, 102));
        rSButtonIconI1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/patent date.png"))); // NOI18N
        rSButtonIconI1.setText("Date birth");
        rSButtonIconI1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(rSButtonIconI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 180, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Doctores  information");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 250, -1));

        rSButtonIconI2.setBackground(new java.awt.Color(0, 0, 102));
        rSButtonIconI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/555 back patent.png"))); // NOI18N
        rSButtonIconI2.setText("    Back to home");
        rSButtonIconI2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonIconI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 200, 50));

        rSButtonIconI4.setBackground(new java.awt.Color(0, 0, 102));
        rSButtonIconI4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/patent name.png"))); // NOI18N
        rSButtonIconI4.setText("Name");
        rSButtonIconI4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(rSButtonIconI4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 50));

        rSButtonIconI3.setBackground(new java.awt.Color(0, 0, 102));
        rSButtonIconI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/patent tell.png"))); // NOI18N
        rSButtonIconI3.setText("Tell");
        rSButtonIconI3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(rSButtonIconI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 130, 50));

        rSButtonIconI5.setBackground(new java.awt.Color(0, 0, 102));
        rSButtonIconI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/patent sex.png"))); // NOI18N
        rSButtonIconI5.setText("SEX");
        rSButtonIconI5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(rSButtonIconI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 130, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/doctors.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 280, 190));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 760));

        jPanel3.setBackground(new java.awt.Color(102, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home / Doctores");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Doctores ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/doctor 2_doctor table.png"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 280, 200));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 980, 200));

        rSButtonMaterialIconTwo1.setBackground(new java.awt.Color(102, 51, 255));
        rSButtonMaterialIconTwo1.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMaterialIconTwo1.setText("Add NEW Doctores");
        rSButtonMaterialIconTwo1.setBackgroundHover(new java.awt.Color(67, 150, 209));
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Manegment  Systeam");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, -1, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/tooth (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, -1));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("Dental clinck ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, -1, 50));

        d_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        d_table.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        d_table.setColorForegroundHead(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(d_table);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 980, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1320, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo1ActionPerformed
        // TODO add your handling code here:
        
        doctor_2 p=new doctor_2 ();
        p.show();
    }//GEN-LAST:event_rSButtonMaterialIconTwo1ActionPerformed

    private void rSButtonIconI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI2ActionPerformed
        // TODO add your handling code here:
        
        dhashbord d= new   dhashbord ();
        d.show();
        this.hide();
    }//GEN-LAST:event_rSButtonIconI2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.TableMetro d_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private rojerusan.RSButtonIconI rSButtonIconI1;
    private rojerusan.RSButtonIconI rSButtonIconI2;
    private rojerusan.RSButtonIconI rSButtonIconI3;
    private rojerusan.RSButtonIconI rSButtonIconI4;
    private rojerusan.RSButtonIconI rSButtonIconI5;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    // End of variables declaration//GEN-END:variables
}
