/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import java.sql.Date;

import javax.swing.JFrame;




/**
 *
 * @author REAL COMPUTERS
 */
public class doctor_2 extends javax.swing.JFrame {

    /**
     * Creates new form doctor_2
     */
    database_con CO=new database_con ();
    
    String d_no=null;

       public void clear(){
           
           txt1.setText("");   txt2.setText("");    txt3.setText("");   txt4.setText(""); search.setText("");
       }
     
    public doctor_2() {
        initComponents();
             this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSButtonMaterialIconOne2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne8 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne9 = new RSMaterialComponent.RSButtonMaterialIconOne();
        jLabel6 = new javax.swing.JLabel();
        txt1 = new RSMaterialComponent.RSTextFieldMaterial();
        txt2 = new RSMaterialComponent.RSTextFieldMaterial();
        txt3 = new RSMaterialComponent.RSTextFieldMaterial();
        txt4 = new RSMaterialComponent.RSTextFieldMaterial();
        search = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        date = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(51, 0, 0));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        panel.setToolTipText("");
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Taype");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Birth");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TELL");
        jLabel5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel5FocusGained(evt);
            }
        });
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 40));

        rSButtonMaterialIconOne2.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne2.setText(" insert");
        rSButtonMaterialIconOne2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne2ActionPerformed(evt);
            }
        });
        panel.add(rSButtonMaterialIconOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 190, 60));

        rSButtonMaterialIconOne8.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne8.setText("   update");
        rSButtonMaterialIconOne8.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne8ActionPerformed(evt);
            }
        });
        panel.add(rSButtonMaterialIconOne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 580, 210, 60));

        rSButtonMaterialIconOne9.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne9.setText("delete");
        rSButtonMaterialIconOne9.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne9ActionPerformed(evt);
            }
        });
        panel.add(rSButtonMaterialIconOne9, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 580, 160, 60));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sex");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 40));

        txt1.setBackground(new java.awt.Color(51, 0, 0));
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt1.setPhColor(new java.awt.Color(255, 255, 255));
        txt1.setPlaceholder("Name");
        panel.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 370, -1));

        txt2.setBackground(new java.awt.Color(51, 0, 0));
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt2.setPhColor(new java.awt.Color(255, 255, 255));
        txt2.setPlaceholder("TELL");
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        panel.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 370, -1));

        txt3.setBackground(new java.awt.Color(51, 0, 0));
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt3.setPhColor(new java.awt.Color(255, 255, 255));
        txt3.setPlaceholder("Taype");
        panel.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 370, 50));

        txt4.setBackground(new java.awt.Color(51, 0, 0));
        txt4.setForeground(new java.awt.Color(255, 255, 255));
        txt4.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt4.setPhColor(new java.awt.Color(255, 255, 255));
        txt4.setPlaceholder("SEX");
        txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt4ActionPerformed(evt);
            }
        });
        panel.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 370, -1));

        search.setBackground(new java.awt.Color(51, 0, 0));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setColorMaterial(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        search.setPhColor(new java.awt.Color(255, 255, 255));
        search.setPlaceholder("Search");
        panel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 340, -1));

        rSButtonIconOne1.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });
        panel.add(rSButtonIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, -1));

        date.setBackground(new java.awt.Color(0, 0, 102));
        date.setForeground(new java.awt.Color(0, 0, 102));
        panel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 360, 50));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5FocusGained

    private void rSButtonMaterialIconOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne2ActionPerformed
        // TODO add your handling code here:
        Date da=new Date(date.getDate().getTime());
        String oprtion="insert";
        String Sql="call doctores_pr('"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+txt4.getText()+"','"+da+"','"+oprtion+"',null)"; ;
        CO.setSql(Sql);
        clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne2ActionPerformed

    private void rSButtonMaterialIconOne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne8ActionPerformed
        Date da=new Date(date.getDate().getTime());
        String oper="update";
        String query = "call doctores_pr('"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+txt4.getText()+"','"+da+"','"+oper+"','"+d_no+"')";
        CO.setSql(query);
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconOne8ActionPerformed

    private void rSButtonMaterialIconOne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne9ActionPerformed
        // TODO add your handling code here:

        Date da=new Date(date.getDate().getTime());
        String oper="delete";
        String query = "call doctores_pr('"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+txt4.getText()+"','"+da+"','"+oper+"','"+d_no+"')";
        CO.setSql(query);
        clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne9ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt4ActionPerformed

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        // TODO add your handling code here:

        String sql="select * from  doctores where d_no='"+search.getText()+"'";
        CO.search(sql);
        try{
            if(CO.rs.next()){
                d_no=CO.rs.getString("d_no");
                txt1.setText(CO.rs.getString("d_name"));
                txt2.setText(CO.rs.getString("d_tell"));
                txt3.setText(CO.rs.getString("d_taype"));
                txt4.setText(CO.rs.getString("sex"));
                date.setDate(CO.rs.getDate("date_birth"));

            }else{
                javax.swing.JOptionPane.showMessageDialog(null,search.getText()+" is not exist");
            }

        }catch(Exception e){

        }

    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(doctor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(doctor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(doctor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(doctor_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new doctor_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne2;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne8;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne9;
    private RSMaterialComponent.RSTextFieldMaterial search;
    private RSMaterialComponent.RSTextFieldMaterial txt1;
    private RSMaterialComponent.RSTextFieldMaterial txt2;
    private RSMaterialComponent.RSTextFieldMaterial txt3;
    private RSMaterialComponent.RSTextFieldMaterial txt4;
    // End of variables declaration//GEN-END:variables
}
