/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import javax.swing.JFrame;

/**
 *
 * @author REAL COMPUTERS
 */
public class login_s extends javax.swing.JFrame {

    /**
     * Creates new form login_s
     */
    public login_s() {
        database_con co=new database_con();
      
         
         initComponents();
        
          
        this.setLocationRelativeTo(null);
      this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSLabelImage1 = new rojerusan.RSLabelImage();
        jLabel1 = new javax.swing.JLabel();
        labelIcon2 = new necesario.LabelIcon();
        labelIcon1 = new necesario.LabelIcon();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        rSMetroTextPlaceHolderBeanInfo1 = new rojerusan.RSMetroTextPlaceHolderBeanInfo();
        rSButtonMaterialOne1 = new RSMaterialComponent.RSButtonMaterialOne();
        rSButtonGradientIcon_new1 = new newscomponents.RSButtonGradientIcon_new();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSLabelImage4 = new rojerusan.RSLabelImage();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSButtonIconI5 = new rojerusan.RSButtonIconI();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        rSLabelImage5 = new rojerusan.RSLabelImage();
        rSButtonIconI2 = new rojerusan.RSButtonIconI();
        rSButtonIconI3 = new rojerusan.RSButtonIconI();
        pass = new necesario.TextField();
        user = new necesario.TextField();
        jPanel2 = new javax.swing.JPanel();

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/download.jpeg"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/dental5.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        rSButtonMaterialOne1.setText("rSButtonMaterialOne1");

        rSButtonGradientIcon_new1.setText("rSButtonGradientIcon_new1");

        rSButtonIconOne1.setBackground(new java.awt.Color(0, 0, 102));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(255, 255, 255));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 51, 255));
        jLabel4.setText("System Java");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 440, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Denteal clinic manegment systeam");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 660, 50));

        rSLabelImage4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/dental4.jpg"))); // NOI18N
        jPanel1.add(rSLabelImage4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 720));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter your password please");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter user name please");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 130, -1, -1));

        rSButtonIconI5.setBackground(new java.awt.Color(0, 0, 102));
        rSButtonIconI5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/home (1).png"))); // NOI18N
        rSButtonIconI5.setText("      Home                    ");
        rSButtonIconI5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rSButtonIconI5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 280, 80));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/password login.png"))); // NOI18N
        jPanel1.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 260, 70, 70));

        rSLabelImage5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/pass user.png"))); // NOI18N
        jPanel1.add(rSLabelImage5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 140, 70, 70));

        rSButtonIconI2.setBackground(new java.awt.Color(107, 19, 19));
        rSButtonIconI2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/log-in (1).png"))); // NOI18N
        rSButtonIconI2.setText("log in");
        rSButtonIconI2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonIconI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 510, 160, 50));

        rSButtonIconI3.setBackground(new java.awt.Color(107, 19, 19));
        rSButtonIconI3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imge/log-in (1).png"))); // NOI18N
        rSButtonIconI3.setText("For get password");
        rSButtonIconI3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rSButtonIconI3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconI3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 360, 290, 60));

        pass.setPlaceholder("enter your national id");
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 280, 270, 40));

        user.setPlaceholder("enter your national id");
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 170, -1, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1640, 720));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        // TODO add your handling code here:

     
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void rSButtonIconI5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonIconI5ActionPerformed

    private void rSButtonIconI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI2ActionPerformed
        // TODO add your handling code here:
        
        
         try{
            database_con co=new database_con();
            String sql=" select * from  users where user_name='"+user.getText()+"' and passwor='"+pass.getText()+"'";
            co.search(sql);
            if(co.rs.next()){
                 dhashbord d=new  dhashbord();
                d.show();
                
                

                this.hide();
                dhashbord.l1.setText(co.rs.getString("user_name"));
                dhashbord.l2.setText(co.rs.getString("user_taype"));
                if(dhashbord.l2.getText().equals("Admin")){
                dhashbord.reg.setVisible(true);
                dhashbord.d1.setVisible(true);
                dhashbord.fin1.setVisible(true);
                dhashbord.aad.setVisible(true);
               
                dhashbord.rep.setVisible(true);
                }
                else if (dhashbord.l2.getText().equals("Dector")){	

                    
                 dhashbord.reg.setVisible(false);
                dhashbord.d1.setVisible(true);
                dhashbord.fin1.setVisible(false);
                 dhashbord.rep.setVisible(false);
                  dhashbord.aad.setVisible(false);
                  
                 
                    
                }
                  else if (dhashbord.l2.getText().equals("fin")){
                    
                 dhashbord.reg.setVisible(false);
                dhashbord.d1.setVisible(false);
                dhashbord.fin1.setVisible(true);
                 dhashbord.rep.setVisible(false);
                  dhashbord.aad.setVisible(false);
                 
                    
                }
                
                
                else{
                    dhashbord.reg.setVisible(true);
            
                dhashbord.rep.setVisible(false);
                dhashbord.d1.setVisible(false);
                dhashbord.fin1.setVisible(false);
                dhashbord.aad.setVisible(false);
                
                
                
                }
                

            }

            else
            javax.swing.JOptionPane.showMessageDialog(null, "incorrect user");

        }catch(Exception ex){
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());

        }// TODO add your handling code here:

    }//GEN-LAST:event_rSButtonIconI2ActionPerformed

    private void rSButtonIconI3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconI3ActionPerformed
        // TODO add your handling code here:
         forget_password  k  = new  forget_password ();
         k.show();
    }//GEN-LAST:event_rSButtonIconI3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_s().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private necesario.LabelIcon labelIcon1;
    private necesario.LabelIcon labelIcon2;
    private necesario.TextField pass;
    private newscomponents.RSButtonGradientIcon_new rSButtonGradientIcon_new1;
    private rojerusan.RSButtonIconI rSButtonIconI2;
    private rojerusan.RSButtonIconI rSButtonIconI3;
    private rojerusan.RSButtonIconI rSButtonIconI5;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonMaterialOne rSButtonMaterialOne1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelImage rSLabelImage3;
    private rojerusan.RSLabelImage rSLabelImage4;
    private rojerusan.RSLabelImage rSLabelImage5;
    private rojerusan.RSMetroTextPlaceHolderBeanInfo rSMetroTextPlaceHolderBeanInfo1;
    private necesario.TextField user;
    // End of variables declaration//GEN-END:variables
}
