/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import java.sql.Date;
import javax.swing.JFrame;

/**
 *
 * @author REAL COMPUTERS
 */
public class opration extends javax.swing.JFrame {

    database_con c=new database_con();
    String id=null;
    String visits=null;
    String services=null;
      String wa;
  String wb;
      public void clear(){
        des.setText("");search.setText("");
    }
    public opration() {
        initComponents();
              this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        
        
        c.fillComboBox(v,"select concat(v_no,',',v_date)visits from  `visits`","visits");
        c.fillComboBox(se,"select concat(ser_no,',',ser_name,',',price)services from  `services`","services");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        v = new RSMaterialComponent.RSComboBox();
        se = new RSMaterialComponent.RSComboBox();
        date = new com.toedter.calendar.JDateChooser();
        rSButtonMaterialIconOne5 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne7 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne3 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        search = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        date1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        v.setBackground(new java.awt.Color(51, 0, 51));
        v.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Visit" }));
        v.setColorArrow(new java.awt.Color(102, 0, 102));
        v.setColorFondo(new java.awt.Color(51, 0, 51));
        v.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vActionPerformed(evt);
            }
        });
        jPanel1.add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 410, 40));

        se.setBackground(new java.awt.Color(51, 0, 51));
        se.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Servise" }));
        se.setColorArrow(new java.awt.Color(102, 0, 102));
        se.setColorFondo(new java.awt.Color(51, 0, 51));
        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });
        jPanel1.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 410, 40));

        date.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 400, 40));

        rSButtonMaterialIconOne5.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne5.setText("Insert");
        rSButtonMaterialIconOne5.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne5.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconOne5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconOne5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 140, -1));

        rSButtonMaterialIconOne7.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne7.setText("Update");
        rSButtonMaterialIconOne7.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne7.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne7ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconOne7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 140, -1));

        rSButtonMaterialIconOne3.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne3.setText("Delete");
        rSButtonMaterialIconOne3.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 140, -1));

        rSButtonIconOne1.setBackground(new java.awt.Color(51, 0, 51));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(255, 255, 255));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, -1, -1));

        search.setBackground(new java.awt.Color(51, 0, 0));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setColorMaterial(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        search.setPhColor(new java.awt.Color(255, 255, 255));
        search.setPlaceholder("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 310, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Servise");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("App_date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Visit");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("oper_date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, -1, -1));

        date1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 400, 40));

        des.setBackground(new java.awt.Color(51, 0, 0));
        des.setColumns(20);
        des.setForeground(new java.awt.Color(255, 255, 255));
        des.setRows(5);
        des.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        des.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(des);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 400, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("description");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vActionPerformed
        // TODO add your handling code here:
        String []ww=v.getSelectedItem().toString().split(",");
       visits=ww[0];
    }//GEN-LAST:event_vActionPerformed

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        // TODO add your handling code here:
        String []ww=se.getSelectedItem().toString().split(",");
        services=ww[0];
    }//GEN-LAST:event_seActionPerformed

    private void rSButtonMaterialIconOne5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne5ActionPerformed
        // TODO add your handling code here:
        Date d=new  Date(date.getDate().getTime());
        Date d1=new  Date(date1.getDate().getTime());

        String oper="insert";
        String Sql="call operations_pr('"+visits+"','"+services+"','"+d+"','"+d1+"','"+des.getText()+"','"+oper+"',null)";
        c.setSql(Sql);
        clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne5ActionPerformed

    private void rSButtonMaterialIconOne7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne7ActionPerformed
        // TODO add your handling code here:
        Date d= new Date(date.getDate().getTime());
         Date d1=new  Date(date1.getDate().getTime());
        String oper="update";
        c.setSql(" call operations_pr('"+visits+"','"+ services+"','"+d+"','"+d1+"','"+des.getText()+"','"+oper+"','"+id+"' )");
        clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne7ActionPerformed

    private void rSButtonMaterialIconOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne3ActionPerformed
        // TODO add your handling code here:\
        Date d= new Date(date.getDate().getTime());
         Date d1=new  Date(date1.getDate().getTime());
        String oper="delete";
        c.setSql(" call operations_pr('"+visits+"','"+ services+"','"+d+"','"+d1+"','"+des.getText()+"','"+oper+"','"+id+"')");
        clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne3ActionPerformed

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        // TODO add your handling code here:

        String sql="SELECT o.oper_no,o.oper_date,o.app_date,o.description ,concat(v.v_no,',',v.v_date)visits, concat(s.ser_no,',',s.ser_name,',',s.price)services   from   services s , operations o ,visits v   WHERE o.ser_no=s.ser_no and o.v_no=v.v_no and o.oper_no='"+search.getText()+"'"; c.search(sql);
        c.search(sql);
        try{
            if(c.rs.next()){
                id=c.rs.getString("oper_no");
                v.setSelectedItem(c.rs.getString("visits"));
                se.setSelectedItem(c.rs.getString("services"));
                date.setDate(c.rs.getDate("oper_date"));
                  date1.setDate(c.rs.getDate("app_date"));
                    des.setText(c.rs.getString("description"));

            }else{
                javax.swing.JOptionPane.showMessageDialog(null, "Record Not Found");

            }

        }catch(Exception ex){

            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());

        }
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private com.toedter.calendar.JDateChooser date1;
    private javax.swing.JTextArea des;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne3;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne5;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne7;
    private RSMaterialComponent.RSComboBox se;
    private RSMaterialComponent.RSTextFieldMaterial search;
    private RSMaterialComponent.RSComboBox v;
    // End of variables declaration//GEN-END:variables
}
