/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import java.sql.Date;

import javax.swing.JFrame;


/**
 *
 * @author REAL COMPUTERS
 */
public class patients_form extends javax.swing.JFrame {

    /**
     * Creates new form patients_form
     */database_con CO=new database_con ();
String p_no=null;
 public void clear(){
       
       txt1.setText("");txt2.setText(""); txt3.setText("");search.setText("");
   }
    public patients_form() {
        initComponents();
             this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rSButtonMaterialIconOne2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne8 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne9 = new RSMaterialComponent.RSButtonMaterialIconOne();
        jLabel6 = new javax.swing.JLabel();
        txt1 = new RSMaterialComponent.RSTextFieldMaterial();
        txt3 = new RSMaterialComponent.RSTextFieldMaterial();
        search = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        date = new com.toedter.calendar.JDateChooser();
        txt2 = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setBackground(new java.awt.Color(51, 0, 0));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 100, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Birth");
        panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 100, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TELL");
        panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, 40));

        rSButtonMaterialIconOne2.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne2.setText(" insert");
        rSButtonMaterialIconOne2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne2ActionPerformed(evt);
            }
        });
        panel.add(rSButtonMaterialIconOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 140, 50));

        rSButtonMaterialIconOne8.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne8.setText("update");
        rSButtonMaterialIconOne8.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne8.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne8ActionPerformed(evt);
            }
        });
        panel.add(rSButtonMaterialIconOne8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 150, 50));

        rSButtonMaterialIconOne9.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne9.setText("delete");
        rSButtonMaterialIconOne9.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne9.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne9ActionPerformed(evt);
            }
        });
        panel.add(rSButtonMaterialIconOne9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 150, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sex");
        panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 40));

        txt1.setBackground(new java.awt.Color(51, 0, 0));
        txt1.setForeground(new java.awt.Color(255, 255, 255));
        txt1.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt1.setPhColor(new java.awt.Color(255, 255, 255));
        txt1.setPlaceholder("Name");
        panel.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 380, -1));

        txt3.setBackground(new java.awt.Color(51, 0, 0));
        txt3.setForeground(new java.awt.Color(255, 255, 255));
        txt3.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt3.setPhColor(new java.awt.Color(255, 255, 255));
        txt3.setPlaceholder("SEX");
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        panel.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 380, -1));

        search.setBackground(new java.awt.Color(51, 0, 0));
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setColorMaterial(new java.awt.Color(255, 255, 255));
        search.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        search.setPhColor(new java.awt.Color(255, 255, 255));
        search.setPlaceholder("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        panel.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 300, 40));

        rSButtonIconOne1.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(255, 255, 255));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });
        panel.add(rSButtonIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));
        panel.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 380, 40));

        txt2.setBackground(new java.awt.Color(51, 0, 0));
        txt2.setForeground(new java.awt.Color(255, 255, 255));
        txt2.setColorMaterial(new java.awt.Color(255, 255, 255));
        txt2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt2.setPhColor(new java.awt.Color(255, 255, 255));
        txt2.setPlaceholder("Name");
        panel.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne2ActionPerformed
        // TODO add your handling code here:
   Date da=new Date(date.getDate().getTime());
        String oprtion="insert";
        String Sql="call patentes_pr('"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+da+"','"+oprtion+"',null)"; ;
        CO.setSql(Sql);
    }//GEN-LAST:event_rSButtonMaterialIconOne2ActionPerformed

    private void rSButtonMaterialIconOne8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne8ActionPerformed
 Date da=new Date(date.getDate().getTime());
        String oper="update";
        String query = "call patentes_pr('"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+da+"','"+oper+"','"+p_no+"')";
        CO.setSql(query);
        clear();
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonMaterialIconOne8ActionPerformed

    private void rSButtonMaterialIconOne9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne9ActionPerformed
        // TODO add your handling code here:
         Date da=new Date(date.getDate().getTime());
        String oper="delete";
        String query = "call patentes_pr('"+txt1.getText()+"','"+txt2.getText()+"','"+txt3.getText()+"','"+da+"','"+oper+"','"+p_no+"')";
        CO.setSql(query);
        clear();
        
    
    }//GEN-LAST:event_rSButtonMaterialIconOne9ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt3ActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchActionPerformed

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        // TODO add your handling code here:

        String sql="select * from  patentes where p_no='"+search.getText()+"'";
        CO.search(sql);
        try{
            if(CO.rs.next()){
                p_no=CO.rs.getString("p_no");
                txt1.setText(CO.rs.getString("p_name"));
                txt2.setText(CO.rs.getString("p_tell"));
                txt3.setText(CO.rs.getString("p_sex"));
                date.setDate(CO.rs.getDate("p_birth"));
            

            }else{
                 javax.swing.JOptionPane.showMessageDialog(null,search.getText()+" is not exist");
            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(patients_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(patients_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(patients_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(patients_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new patients_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panel;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne2;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne8;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne9;
    private RSMaterialComponent.RSTextFieldMaterial search;
    private RSMaterialComponent.RSTextFieldMaterial txt1;
    private RSMaterialComponent.RSTextFieldMaterial txt2;
    private RSMaterialComponent.RSTextFieldMaterial txt3;
    // End of variables declaration//GEN-END:variables
}
