/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import java.sql.Date;
import javax.swing.JFrame;

/**\
 * 
 *
 * @author REAL COMPUTERS
 */
public class recepts extends javax.swing.JFrame {

     database_con CO=new database_con ();

String receipts=null;
 String patentes=null;
  String account=null;

  String wa;
  String wb;
      public void clear(){
        t1.setText("");t2.setText("");
    }
  
  
    public recepts() {
        initComponents();
              this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         
          CO.fillComboBox(comb1, "SELECT concat(p_no,',',p_name,',',p_tell)patentes FROM `patentes`", "patentes");
            CO.fillComboBox(comb2, "SELECT concat(acc_no,',',acc_name,',',balance)account FROM `account`", "account");
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        comb2 = new RSMaterialComponent.RSComboBox();
        comb1 = new RSMaterialComponent.RSComboBox();
        t1 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        d = new javax.swing.JTextArea();
        rSButtonMaterialIconTwo1 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        date = new com.toedter.calendar.JDateChooser();
        t2 = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        rSButtonMaterialIconTwo2 = new RSMaterialComponent.RSButtonMaterialIconTwo();
        rSButtonMaterialIconTwo3 = new RSMaterialComponent.RSButtonMaterialIconTwo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acount" }));
        comb2.setColorFondo(new java.awt.Color(51, 0, 51));
        comb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb2ActionPerformed(evt);
            }
        });
        jPanel2.add(comb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 380, -1));

        comb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "patients" }));
        comb1.setColorBorde(new java.awt.Color(255, 51, 102));
        comb1.setColorDisabledIndexText(new java.awt.Color(51, 51, 255));
        comb1.setColorFondo(new java.awt.Color(51, 0, 51));
        comb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb1ActionPerformed(evt);
            }
        });
        jPanel2.add(comb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 380, 40));

        t1.setBackground(new java.awt.Color(51, 0, 0));
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setColorMaterial(new java.awt.Color(255, 255, 255));
        t1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t1.setPhColor(new java.awt.Color(255, 255, 255));
        t1.setPlaceholder("Search");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 250, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("description");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("patients");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("amount");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Acont");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 70, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("date");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        d.setBackground(new java.awt.Color(51, 0, 0));
        d.setColumns(20);
        d.setForeground(new java.awt.Color(255, 255, 255));
        d.setRows(5);
        d.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        d.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(d);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 380, 70));

        rSButtonMaterialIconTwo1.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconTwo1.setText("INSERT");
        rSButtonMaterialIconTwo1.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconTwo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconTwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconTwo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 160, 60));

        date.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 380, 30));

        t2.setBackground(new java.awt.Color(51, 0, 0));
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setColorMaterial(new java.awt.Color(255, 255, 255));
        t2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t2.setPhColor(new java.awt.Color(255, 255, 255));
        t2.setPlaceholder("Amount");
        jPanel2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 380, 30));

        rSButtonIconOne1.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(51, 0, 0));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        rSButtonMaterialIconTwo2.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconTwo2.setText("UPDATE");
        rSButtonMaterialIconTwo2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconTwo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconTwo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo2ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconTwo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 170, 60));

        rSButtonMaterialIconTwo3.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconTwo3.setText("Delete");
        rSButtonMaterialIconTwo3.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconTwo3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconTwo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconTwo3ActionPerformed(evt);
            }
        });
        jPanel2.add(rSButtonMaterialIconTwo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 150, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconTwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo1ActionPerformed
        // TODO add your handling code here:
        
        Date da=new Date(date.getDate().getTime());
                 String oper="insert";
                 
        String Sql="call receipts_pr('"+patentes+"','"+t2.getText()+"','"+account+"','"+da+"',"
                + "'"+d.getText()+"','"+oper+"',null)";
         CO.setSql(Sql);
         clear();
    }//GEN-LAST:event_rSButtonMaterialIconTwo1ActionPerformed

    private void comb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb1ActionPerformed
     String []ww=comb1.getSelectedItem().toString().split(",");
     patentes=ww[0];
    }//GEN-LAST:event_comb1ActionPerformed

    private void comb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb2ActionPerformed
        String []ww=comb2.getSelectedItem().toString().split(",");
     account=ww[0];
    }//GEN-LAST:event_comb2ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        // TODO add your handling code here:
         
          String sql="SELECT r.rn_no,r.amounts,r.rec_date,r.description,concat(p.p_no,',',p.p_name, ',',p.p_tell) patentes,  concat(a.acc_no,',',a.acc_name ,',',a.balance) account  from patentes p , receipts r ,account a   WHERE r.p_no=p.p_no and r.acc_no=a.acc_no and rn_no='"+t1.getText()+"'"; CO.search(sql);
                 
    CO.search(sql); 
    try{
        if(CO.rs.next()){
            receipts=CO.rs.getString("rn_no");
            comb1.setSelectedItem(CO.rs.getString("patentes"));
             t2.setText(CO.rs.getString("amounts"));
            comb2.setSelectedItem(CO.rs.getString("account"));
            date.setDate(CO.rs.getDate("rec_date"));
            
             d.setText(CO.rs.getString("description"));
           
           
          
            
        }else{
            
             javax.swing.JOptionPane.showMessageDialog(null,"Record Not Found");
        }
        
    }catch(Exception ex){
        javax.swing.JOptionPane.showMessageDialog(null,ex.getMessage());
    }
        
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void rSButtonMaterialIconTwo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo2ActionPerformed
        // TODO add your handling code here:
                Date da=new Date(date.getDate().getTime());
           String oper="update";
        CO.setSql("call receipts_pr('"+patentes+"','"+t1.getText()+"','"+account+"','"+da+"','"+d.getText()+"','"+oper+"','"+receipts+"')");
        clear();
        
    }//GEN-LAST:event_rSButtonMaterialIconTwo2ActionPerformed

    private void rSButtonMaterialIconTwo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconTwo3ActionPerformed
        // TODO add your handling code here:
                    Date da=new Date(date.getDate().getTime());
           String oper="delete";
        CO.setSql("call receipts_pr('"+patentes+"','"+t1.getText()+"','"+account+"','"+da+"','"+d.getText()+"','"+oper+"','"+receipts+"')");
        clear();
    }//GEN-LAST:event_rSButtonMaterialIconTwo3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recepts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recepts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSComboBox comb1;
    private RSMaterialComponent.RSComboBox comb2;
    private javax.swing.JTextArea d;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo1;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo2;
    private RSMaterialComponent.RSButtonMaterialIconTwo rSButtonMaterialIconTwo3;
    private RSMaterialComponent.RSTextFieldMaterial t1;
    private RSMaterialComponent.RSTextFieldMaterial t2;
    // End of variables declaration//GEN-END:variables
}
