/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a_dentelclinck;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author REAL COMPUTERS
 */
public class user_form extends javax.swing.JFrame {

   database_con CO=new database_con ();
String user_no=null;

String comb="";

   public void clear(){
       
       t1.setText("");   t2.setText("");   t3.setText("");   t4.setText("");   t5.setText("");   t6.setText("");   
   }
    public user_form() {
        initComponents();
          this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t2 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rSButtonMaterialIconOne2 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne3 = new RSMaterialComponent.RSButtonMaterialIconOne();
        rSButtonMaterialIconOne4 = new RSMaterialComponent.RSButtonMaterialIconOne();
        t1 = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonIconOne1 = new RSMaterialComponent.RSButtonIconOne();
        t4 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel3 = new javax.swing.JLabel();
        taype = new RSMaterialComponent.RSComboBoxMaterial();
        jLabel4 = new javax.swing.JLabel();
        t5 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel5 = new javax.swing.JLabel();
        t6 = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel6 = new javax.swing.JLabel();
        t3 = new RSMaterialComponent.RSTextFieldMaterial();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.setBackground(new java.awt.Color(51, 0, 0));
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setColorMaterial(new java.awt.Color(255, 255, 255));
        t2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t2.setPhColor(new java.awt.Color(255, 255, 255));
        t2.setPlaceholder("Password");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 320, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("national_Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User_taype");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        rSButtonMaterialIconOne2.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne2.setText("Delete");
        rSButtonMaterialIconOne2.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        rSButtonMaterialIconOne2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconOne2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 140, -1));

        rSButtonMaterialIconOne3.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne3.setText("Insert");
        rSButtonMaterialIconOne3.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne3.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_BOX);
        rSButtonMaterialIconOne3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconOne3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 140, -1));

        rSButtonMaterialIconOne4.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonMaterialIconOne4.setText("Update");
        rSButtonMaterialIconOne4.setFont(new java.awt.Font("Roboto Bold", 1, 24)); // NOI18N
        rSButtonMaterialIconOne4.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.UPDATE);
        rSButtonMaterialIconOne4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconOne4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonMaterialIconOne4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, 140, -1));

        t1.setBackground(new java.awt.Color(51, 0, 0));
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setColorMaterial(new java.awt.Color(255, 255, 255));
        t1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t1.setPhColor(new java.awt.Color(255, 255, 255));
        t1.setPlaceholder("Name");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 320, 40));

        rSButtonIconOne1.setBackground(new java.awt.Color(51, 0, 0));
        rSButtonIconOne1.setBackgroundHover(new java.awt.Color(255, 255, 255));
        rSButtonIconOne1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SEARCH);
        rSButtonIconOne1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonIconOne1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButtonIconOne1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        t4.setBackground(new java.awt.Color(51, 0, 0));
        t4.setForeground(new java.awt.Color(255, 255, 255));
        t4.setColorMaterial(new java.awt.Color(255, 255, 255));
        t4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t4.setPhColor(new java.awt.Color(255, 255, 255));
        t4.setPlaceholder("Email");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 320, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        taype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Dector", "User", "fin" }));
        jPanel1.add(taype, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 330, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        t5.setBackground(new java.awt.Color(51, 0, 0));
        t5.setForeground(new java.awt.Color(255, 255, 255));
        t5.setColorMaterial(new java.awt.Color(255, 255, 255));
        t5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t5.setPhColor(new java.awt.Color(255, 255, 255));
        t5.setPlaceholder("Name");
        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        jPanel1.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 320, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Emial");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 130, -1));

        t6.setBackground(new java.awt.Color(51, 0, 0));
        t6.setForeground(new java.awt.Color(255, 255, 255));
        t6.setColorMaterial(new java.awt.Color(255, 255, 255));
        t6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t6.setPhColor(new java.awt.Color(255, 255, 255));
        t6.setPlaceholder("ID");
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        jPanel1.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 320, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("mother_name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 170, -1));

        t3.setBackground(new java.awt.Color(51, 0, 0));
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setColorMaterial(new java.awt.Color(255, 255, 255));
        t3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t3.setPhColor(new java.awt.Color(255, 255, 255));
        t3.setPlaceholder("ID");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 340, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMaterialIconOne2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne2ActionPerformed
        // TODO add your handling code here:

       String oper="delete";
 String query = "call user_new_pr('"+t1.getText()+"','"+taype.getSelectedItem()+"','"+t2.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+t6.getText()+"','"+oper +"','"+user_no+"')";
    CO.setSql(query);
    clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne2ActionPerformed

    private void rSButtonMaterialIconOne3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne3ActionPerformed
        // TODO add your handling code here:
        
        
            String oprtion="insert";
            
            String Sql="call user_new_pr('"+t1.getText()+"','"+taype.getSelectedItem()+"','"+t2.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+t6.getText()+"','"+oprtion +"',null)"; ;
            CO.setSql(Sql);
            clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne3ActionPerformed

    private void rSButtonMaterialIconOne4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconOne4ActionPerformed

        // TODO add your handling code here:
        
        
 String oper="update";
 String query = "call user_new_pr('"+t1.getText()+"','"+taype.getSelectedItem()+"','"+t2.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+t6.getText()+"','"+oper +"','"+user_no+"')";
    CO.setSql(query);
    clear();
    }//GEN-LAST:event_rSButtonMaterialIconOne4ActionPerformed

    private void rSButtonIconOne1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonIconOne1ActionPerformed
        // TODO add your handling code here:
       
               String sql="select user_no,user_name,user_taype,passwor,user_emial,user_mother_name,user_natinol_id  from users where user_no='"+t3.getText()+"'";
       CO.search(sql);
       try{
           if(CO.rs.next()){
               user_no=CO.rs.getString("user_no");
               t1.setText(CO.rs.getString("user_name"));
               
                 taype.setSelectedItem(CO.rs.getString("user_taype"));
               t2.setText(CO.rs.getString("passwor"));
                 t4.setText(CO.rs.getString("user_emial"));
          
                    t5.setText(CO.rs.getString("user_mother_name"));
               t6.setText(CO.rs.getString("user_natinol_id"));
                   
           
               
              
              
              
              
               
           }else{
               JOptionPane.showMessageDialog(null,t3.getText()+" is not exist");
           }
           
       }catch(Exception e){
           
       }
    }//GEN-LAST:event_rSButtonIconOne1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private RSMaterialComponent.RSButtonIconOne rSButtonIconOne1;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne2;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne3;
    private RSMaterialComponent.RSButtonMaterialIconOne rSButtonMaterialIconOne4;
    private RSMaterialComponent.RSTextFieldMaterial t1;
    private RSMaterialComponent.RSTextFieldMaterial t2;
    private RSMaterialComponent.RSTextFieldMaterial t3;
    private RSMaterialComponent.RSTextFieldMaterial t4;
    private RSMaterialComponent.RSTextFieldMaterial t5;
    private RSMaterialComponent.RSTextFieldMaterial t6;
    private RSMaterialComponent.RSComboBoxMaterial taype;
    // End of variables declaration//GEN-END:variables
}
